# Generated by Django 5.1.5 on 2025-01-31 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('am_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salary')),
            ],
        ),
    ]
