# Generated by Django 5.1.5 on 2025-01-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.salary'),
        ),
    ]
